version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "reactions"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15sa10cjhp6n9"
s3_prefix = "reactions"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
